server:
  port: 8080

spring:
  application:
    name: zhongyiguan-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

